# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: power_bookmark_specifics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import note_entity_pb2 as note__entity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='power_bookmark_specifics.proto',
  package='sync_pb',
  syntax='proto2',
  serialized_options=b'\n%org.chromium.components.sync.protocolH\003P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1epower_bookmark_specifics.proto\x12\x07sync_pb\x1a\x11note_entity.proto\"C\n\x0bPowerEntity\x12*\n\x0bnote_entity\x18\x02 \x01(\x0b\x32\x13.sync_pb.NoteEntityH\x00\x42\x08\n\x06\x65ntity\"\xa7\x02\n\x16PowerBookmarkSpecifics\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12=\n\npower_type\x18\x03 \x01(\x0e\x32).sync_pb.PowerBookmarkSpecifics.PowerType\x12\x1a\n\x12\x63reation_time_usec\x18\x04 \x01(\x03\x12\x18\n\x10update_time_usec\x18\x05 \x01(\x03\x12*\n\x0cpower_entity\x18\x64 \x01(\x0b\x32\x14.sync_pb.PowerEntity\"Q\n\tPowerType\x12\x1a\n\x16POWER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fPOWER_TYPE_MOCK\x10\x01\x12\x13\n\x0fPOWER_TYPE_NOTE\x10\x02\x42+\n%org.chromium.components.sync.protocolH\x03P\x01'
  ,
  dependencies=[note__entity__pb2.DESCRIPTOR,])



_POWERBOOKMARKSPECIFICS_POWERTYPE = _descriptor.EnumDescriptor(
  name='PowerType',
  full_name='sync_pb.PowerBookmarkSpecifics.PowerType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POWER_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POWER_TYPE_MOCK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='POWER_TYPE_NOTE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=346,
  serialized_end=427,
)
_sym_db.RegisterEnumDescriptor(_POWERBOOKMARKSPECIFICS_POWERTYPE)


_POWERENTITY = _descriptor.Descriptor(
  name='PowerEntity',
  full_name='sync_pb.PowerEntity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='note_entity', full_name='sync_pb.PowerEntity.note_entity', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='entity', full_name='sync_pb.PowerEntity.entity',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=62,
  serialized_end=129,
)


_POWERBOOKMARKSPECIFICS = _descriptor.Descriptor(
  name='PowerBookmarkSpecifics',
  full_name='sync_pb.PowerBookmarkSpecifics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='guid', full_name='sync_pb.PowerBookmarkSpecifics.guid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='sync_pb.PowerBookmarkSpecifics.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_type', full_name='sync_pb.PowerBookmarkSpecifics.power_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creation_time_usec', full_name='sync_pb.PowerBookmarkSpecifics.creation_time_usec', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_time_usec', full_name='sync_pb.PowerBookmarkSpecifics.update_time_usec', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='power_entity', full_name='sync_pb.PowerBookmarkSpecifics.power_entity', index=5,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POWERBOOKMARKSPECIFICS_POWERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=427,
)

_POWERENTITY.fields_by_name['note_entity'].message_type = note__entity__pb2._NOTEENTITY
_POWERENTITY.oneofs_by_name['entity'].fields.append(
  _POWERENTITY.fields_by_name['note_entity'])
_POWERENTITY.fields_by_name['note_entity'].containing_oneof = _POWERENTITY.oneofs_by_name['entity']
_POWERBOOKMARKSPECIFICS.fields_by_name['power_type'].enum_type = _POWERBOOKMARKSPECIFICS_POWERTYPE
_POWERBOOKMARKSPECIFICS.fields_by_name['power_entity'].message_type = _POWERENTITY
_POWERBOOKMARKSPECIFICS_POWERTYPE.containing_type = _POWERBOOKMARKSPECIFICS
DESCRIPTOR.message_types_by_name['PowerEntity'] = _POWERENTITY
DESCRIPTOR.message_types_by_name['PowerBookmarkSpecifics'] = _POWERBOOKMARKSPECIFICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerEntity = _reflection.GeneratedProtocolMessageType('PowerEntity', (_message.Message,), {
  'DESCRIPTOR' : _POWERENTITY,
  '__module__' : 'power_bookmark_specifics_pb2'
  # @@protoc_insertion_point(class_scope:sync_pb.PowerEntity)
  })
_sym_db.RegisterMessage(PowerEntity)

PowerBookmarkSpecifics = _reflection.GeneratedProtocolMessageType('PowerBookmarkSpecifics', (_message.Message,), {
  'DESCRIPTOR' : _POWERBOOKMARKSPECIFICS,
  '__module__' : 'power_bookmark_specifics_pb2'
  # @@protoc_insertion_point(class_scope:sync_pb.PowerBookmarkSpecifics)
  })
_sym_db.RegisterMessage(PowerBookmarkSpecifics)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
